# Generated by Django 2.2.2 on 2020-05-24 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_invoice_invoice_item_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_item',
        ),
        migrations.AddField(
            model_name='invoice_item',
            name='invoice',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='mysite.Invoice'),
            preserve_default=False,
        ),
    ]
