# Generated by Django 2.2.2 on 2020-05-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20200524_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.DateField(blank=True, null=True),
        ),
    ]
