# Generated by Django 2.2.2 on 2020-05-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20200524_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='inv_item',
            name='total',
            field=models.FloatField(blank=True, default=2),
            preserve_default=False,
        ),
    ]
