# Generated by Django 2.2.2 on 2020-05-24 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_inv_item_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inv_item',
            name='total',
        ),
    ]
