# Generated by Django 2.2.2 on 2020-05-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_remove_inv_item_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='inv_item',
            name='total',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
